import { AreaId, Chest, Item, Monster, NPC, Portal, Quest, PlayerStats, PlayerSkills, SkillInfo } from '../types';

export const INITIAL_WEAPONS: Item[] = [
  {
    id: 'w_wood',
    name: 'Wooden Sword',
    type: 'weapon',
    value: 5,
    price: 50,
    description: 'Pedang latihan sederhana terbuat dari kayu ek keras.',
    icon: '🪵',
    upgradeLevel: 0,
  },
  {
    id: 'w_iron',
    name: 'Iron Sword',
    type: 'weapon',
    value: 10,
    price: 150,
    description: 'Pedang besi kokoh yang ditempa di pandai besi kerajaan.',
    icon: '⚔️',
    upgradeLevel: 0,
  },
  {
    id: 'w_knight',
    name: 'Knight Sword',
    type: 'weapon',
    value: 20,
    price: 350,
    description: 'Pedang kesatria kerajaan dengan bilah tajam bersepuh baja perak.',
    icon: '🗡️',
    upgradeLevel: 0,
  },
  {
    id: 'w_royal',
    name: 'Royal Sword',
    type: 'weapon',
    value: 35,
    price: 700,
    description: 'Pedang agung lambang kehormatan pengawal istana raja.',
    icon: '👑',
    upgradeLevel: 0,
  },
  {
    id: 'w_slayer',
    name: 'Demon Slayer Blade',
    type: 'weapon',
    value: 55,
    price: 1200,
    description: 'Bilah suci kuno yang beresonansi untuk membasmi iblis kegelapan.',
    icon: '✨',
    upgradeLevel: 0,
  },
];

export const INITIAL_ARMORS: Item[] = [
  {
    id: 'a_leather',
    name: 'Leather Armor',
    type: 'armor',
    value: 5,
    price: 50,
    description: 'Rompi kulit tebal untuk melindungi dari cakaran monster kecil.',
    icon: '🦺',
    upgradeLevel: 0,
  },
  {
    id: 'a_iron',
    name: 'Iron Armor',
    type: 'armor',
    value: 10,
    price: 150,
    description: 'Baju zirah pelat besi tempa standar prajurit kerajaan.',
    icon: '🛡️',
    upgradeLevel: 0,
  },
  {
    id: 'a_knight',
    name: 'Knight Armor',
    type: 'armor',
    value: 20,
    price: 350,
    description: 'Baju zirah kesatria berlapis baja dengan peredam benturan.',
    icon: '🎖️',
    upgradeLevel: 0,
  },
  {
    id: 'a_royal',
    name: 'Royal Armor',
    type: 'armor',
    value: 30,
    price: 700,
    description: 'Zirah kerajaan berornamen emas yang memberikan pertahanan tinggi.',
    icon: '⚜️',
    upgradeLevel: 0,
  },
  {
    id: 'a_demon',
    name: 'Demon Ward Armor',
    type: 'armor',
    value: 45,
    price: 1100,
    description: 'Zirah pelindung suci anti-sihir dan tahan api lahar kegelapan.',
    icon: '💠',
    upgradeLevel: 0,
  },
];

export const INITIAL_POTIONS: Item[] = [
  {
    id: 'pot_health',
    name: 'Health Potion',
    type: 'potion',
    value: 50,
    price: 25,
    description: 'Ramuan herbal merah memulihkan 50 HP kesatria seketika.',
    icon: '🧪',
  },
  {
    id: 'pot_high',
    name: 'High Potion',
    type: 'potion',
    value: 120,
    price: 60,
    description: 'Ramuan penyembuh berkonsentrasi tinggi, memulihkan 120 HP.',
    icon: '🍷',
  },
  {
    id: 'pot_elixir',
    name: 'Royal Elixir',
    type: 'potion',
    value: 999,
    price: 150,
    description: 'Eliksir suci kerajaan yang memulihkan HP pemain hingga penuh!',
    icon: '🌟',
  },
];

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'q1',
    title: 'Ancaman Slime',
    giverName: 'Tetua Kerajaan',
    description: 'Penduduk kerajaan mulai diserang slime di hutan. Kalahkan 5 Slime dan kembali kepadaku.',
    targetMonster: 'slime',
    targetCount: 5,
    currentCount: 0,
    rewardCoin: 100,
    rewardExp: 50,
    isCompleted: false,
    isClaimed: false,
    areaHint: 'Green Forest',
  },
  {
    id: 'q2',
    title: 'Serangan Goblin',
    giverName: 'Penjaga Gerbang',
    description: 'Para Goblin hutan mulai merampas pasokan desa. Kalahkan 5 Goblin untuk mengamankan rute.',
    targetMonster: 'goblin',
    targetCount: 5,
    currentCount: 0,
    rewardCoin: 150,
    rewardExp: 80,
    isCompleted: false,
    isClaimed: false,
    areaHint: 'Green Forest',
  },
  {
    id: 'q3',
    title: 'Penjaga Hutan Purba',
    giverName: 'Tetua Kerajaan',
    description: 'Forest Guardian di Hutan Gelap telah dirasuki sihir gelap Raja Iblis. Kalahkan dia untuk membuka jalan ke Reruntuhan Kuno!',
    targetMonster: 'forest_guardian',
    targetCount: 1,
    currentCount: 0,
    rewardCoin: 300,
    rewardExp: 200,
    isCompleted: false,
    isClaimed: false,
    areaHint: 'Dark Forest',
  },
  {
    id: 'q4',
    title: 'Kutukan Reruntuhan',
    giverName: 'Tetua Kerajaan',
    description: 'Kalahkan Skeleton King di Reruntuhan Kuno untuk menghancurkan segel kegelapan.',
    targetMonster: 'skeleton_king',
    targetCount: 1,
    currentCount: 0,
    rewardCoin: 450,
    rewardExp: 350,
    isCompleted: false,
    isClaimed: false,
    areaHint: 'Ancient Ruins',
  },
  {
    id: 'q5',
    title: 'Panglima Neraka',
    giverName: 'Penjaga Gerbang',
    description: 'Demon General menjaga jembatan menuju Kastil Raja Iblis. Kalahkan dia!',
    targetMonster: 'demon_general',
    targetCount: 1,
    currentCount: 0,
    rewardCoin: 600,
    rewardExp: 500,
    isCompleted: false,
    isClaimed: false,
    areaHint: 'Demon Territory',
  },
  {
    id: 'q6',
    title: 'Taklukkan Raja Iblis',
    giverName: 'Raja Kerajaan',
    description: 'Kalahkan Raja Iblis di tahtanya di Demon Castle agar kedamaian kembali ke dunia!',
    targetMonster: 'demon_king',
    targetCount: 1,
    currentCount: 0,
    rewardCoin: 1500,
    rewardExp: 1000,
    isCompleted: false,
    isClaimed: false,
    areaHint: 'Demon Castle',
  },
];

export const SKILLS_DATA: Record<keyof PlayerSkills, SkillInfo> = {
  whirlwind: {
    id: 'whirlwind',
    name: 'Tebasan Badai',
    description: 'Kesatria berputar cepat menebas semua musuh di sekitarnya dalam radius 360° dengan energi badai dahsyat.',
    icon: '🌪️',
    key: 'Q',
    hotkey: 'Q / 1',
    cooldownSeconds: 5,
    maxLevel: 5,
    previewEffect: 'Area Damage (360°)',
  },
  holyThrust: {
    id: 'holyThrust',
    name: 'Tusukan Cahaya',
    description: 'Menembakkan gelombang pedang cahaya suci berkecepatan tinggi yang menembus garis musuh.',
    icon: '✨',
    key: 'R',
    hotkey: 'R / 2',
    cooldownSeconds: 7,
    maxLevel: 5,
    previewEffect: 'Piercing Holy Beam',
  },
  ironShield: {
    id: 'ironShield',
    name: 'Perisai Benteng',
    description: 'Membangkitkan pelindung suci kebal serangan musuh sementara dan memulihkan HP secara instan.',
    icon: '🛡️',
    key: 'F',
    hotkey: 'F / 3',
    cooldownSeconds: 12,
    maxLevel: 5,
    previewEffect: 'Invulnerability & Heal',
  },
};

export const INITIAL_PLAYER_STATS: PlayerStats = {
  hp: 100,
  maxHp: 100,
  level: 1,
  exp: 0,
  maxExp: 100,
  coin: 100,
  baseDamage: 12,
  baseDefense: 5,
  equippedWeapon: INITIAL_WEAPONS[0],
  equippedArmor: INITIAL_ARMORS[0],
  inventory: [INITIAL_WEAPONS[0], INITIAL_ARMORS[0]],
  potionCount: 3,
  activeQuests: [INITIAL_QUESTS[0]],
  completedQuestIds: [] as string[],
  monstersSlainCount: 0,
  skillPoints: 1,
  skills: {
    whirlwind: 1,
    holyThrust: 0,
    ironShield: 0,
  },
};

export interface AreaData {
  id: AreaId;
  name: string;
  subtitle: string;
  width: number;
  height: number;
  bgFill: string;
  musicTrack: string;
  npcs: NPC[];
  portals: Portal[];
  chests: Chest[];
  monsterSpawns: Array<{
    type: Monster['type'];
    name: string;
    x: number;
    y: number;
    hp: number;
    damage: number;
    defense: number;
    speed: number;
    exp: number;
    coin: number;
    isBoss?: boolean;
    bossTitle?: string;
  }>;
}

export const WORLD_AREAS: Record<AreaId, AreaData> = {
  kingdom: {
    id: 'kingdom',
    name: 'KERINTILAN KERINTAH (KINGDOM)',
    subtitle: 'Area Aman & Ibukota Kerajaan Manusia',
    width: 1800,
    height: 1000,
    bgFill: '#334155', // Cobblestone & courtyard slate
    musicTrack: 'kingdom',
    npcs: [
      {
        id: 'npc_elder',
        name: 'Tetua Almeric',
        role: 'quest',
        x: 820,
        y: 470,
        width: 32,
        height: 32,
        dialogue: [
          'Salam, Kesatria pemberani.',
          'Kekuatan kegelapan Raja Iblis semakin merajalela di luar gerbang!',
          'Monster dan slime mulai mengacaukan pemukiman warga.',
          'Maukah kamu membantu kerajaan menjalankan misi suci ini?',
        ],
        questId: 'q1',
      },
      {
        id: 'npc_guard',
        name: 'Kapten Penjaga Gerbang',
        role: 'guard',
        x: 1640,
        y: 460,
        width: 32,
        height: 32,
        dialogue: [
          'Waspadalah jika keluar dari gerbang kerajaan!',
          'Di Hutan Hijau banyak Slime dan Goblin berkeliaran.',
          'Pastikan pedang dan zirahmu sudah ditingkatkan di pandai besi.',
          'Semoga perlindungan raja menyertai langkahmu!',
        ],
      },
      {
        id: 'npc_weapon',
        name: 'Pedagang Senjata Roland',
        role: 'weapon_shop',
        x: 220,
        y: 260,
        width: 32,
        height: 32,
        shopType: 'weapon',
        dialogue: [
          'Selamat datang di Toko Senjata Roland!',
          'Kami menyediakan bilah terbaik dari besi murni hingga pedang bersepuh emas.',
          'Pilihlah senjatamu untuk menebas monster!',
        ],
      },
      {
        id: 'npc_armor',
        name: 'Pedagang Zirah Hilda',
        role: 'armor_shop',
        x: 520,
        y: 260,
        width: 32,
        height: 32,
        shopType: 'armor',
        dialogue: [
          'Pertahanan yang kokoh menyelamatkan nyawamu!',
          'Zirah besi dan zirah kesatria kami dibuat dengan standar tertinggi.',
          'Lihatlah koleksi zirah pelindung kami.',
        ],
      },
      {
        id: 'npc_blacksmith',
        name: 'Pandai Besi Goran',
        role: 'blacksmith',
        x: 220,
        y: 690,
        width: 32,
        height: 32,
        shopType: 'blacksmith',
        dialogue: [
          '*KLANG! KLANG!*',
          'Bawakan senjatamu atau zirahmu, aku bisa memperkuatnya!',
          'Dengan koin yang cukup, aku bisa menambahkan level peningkatan (+1, +2, +3)!',
        ],
      },
      {
        id: 'npc_item',
        name: 'Tabib Desa Lyra',
        role: 'item_shop',
        x: 520,
        y: 690,
        width: 32,
        height: 32,
        shopType: 'item',
        dialogue: [
          'Jangan pernah bertualang tanpa persediaan Health Potion!',
          'Satu tegukan ramuan herbal ini dapat memulihkan tenagamu di saat genting.',
        ],
      },
      {
        id: 'npc_villager',
        name: 'Penduduk Desa Mina',
        role: 'villager',
        x: 370,
        y: 670,
        width: 32,
        height: 32,
        dialogue: [
          'Dulu hutan sangat damai, kami sering memetik buah beri...',
          'Namun sejak kabar kemunculan Raja Iblis, tak ada yang berani pergi ke Hutan Gelap.',
          'Tolong selamatkan kami, Kesatria!',
        ],
      },
    ],
    portals: [
      {
        id: 'portal_to_forest',
        x: 1720,
        y: 480,
        width: 40,
        height: 60,
        targetArea: 'green_forest',
        targetX: 80,
        targetY: 480,
        label: 'MENUJU GREEN FOREST ▶',
      },
    ],
    chests: [
      { id: 'chest_k1', x: 120, y: 780, opened: false, coin: 80, item: INITIAL_POTIONS[0] },
      { id: 'chest_k2', x: 1550, y: 200, opened: false, coin: 120 },
    ],
    monsterSpawns: [], // Safe Zone: no monsters!
  },

  green_forest: {
    id: 'green_forest',
    name: 'GREEN FOREST',
    subtitle: 'Hutan Hijau Tempat Berseminya Slime & Goblin',
    width: 2000,
    height: 1200,
    bgFill: '#14532d', // Lush grass green
    musicTrack: 'green_forest',
    npcs: [],
    portals: [
      {
        id: 'portal_back_kingdom',
        x: 40,
        y: 480,
        width: 40,
        height: 60,
        targetArea: 'kingdom',
        targetX: 1650,
        targetY: 480,
        label: '◀ KEMBALI KE KERAJAAN',
      },
      {
        id: 'portal_to_dark_forest',
        x: 1920,
        y: 480,
        width: 40,
        height: 60,
        targetArea: 'dark_forest',
        targetX: 80,
        targetY: 480,
        label: 'MENUJU DARK FOREST ▶',
      },
    ],
    chests: [
      { id: 'chest_gf1', x: 500, y: 180, opened: false, coin: 150, item: INITIAL_POTIONS[1] },
      { id: 'chest_gf2', x: 1700, y: 850, opened: false, coin: 200 },
    ],
    monsterSpawns: [
      { type: 'slime', name: 'Blue Slime', x: 260, y: 350, hp: 40, damage: 8, defense: 1, speed: 1.1, exp: 15, coin: 15 },
      { type: 'slime', name: 'Blue Slime', x: 420, y: 650, hp: 40, damage: 8, defense: 1, speed: 1.1, exp: 15, coin: 15 },
      { type: 'green_slime', name: 'Toxic Slime', x: 600, y: 320, hp: 60, damage: 12, defense: 2, speed: 1.2, exp: 22, coin: 25 },
      { type: 'bat', name: 'Cave Bat', x: 800, y: 220, hp: 35, damage: 10, defense: 0, speed: 1.8, exp: 20, coin: 20 },
      { type: 'bat', name: 'Cave Bat', x: 1250, y: 750, hp: 35, damage: 10, defense: 0, speed: 1.8, exp: 20, coin: 20 },
      { type: 'goblin', name: 'Forest Goblin', x: 1350, y: 450, hp: 75, damage: 15, defense: 3, speed: 1.3, exp: 35, coin: 35 },
      { type: 'goblin', name: 'Forest Goblin', x: 1550, y: 350, hp: 75, damage: 15, defense: 3, speed: 1.3, exp: 35, coin: 35 },
      { type: 'slime', name: 'Blue Slime', x: 850, y: 850, hp: 40, damage: 8, defense: 1, speed: 1.1, exp: 15, coin: 15 },
      { type: 'green_slime', name: 'Toxic Slime', x: 1650, y: 650, hp: 60, damage: 12, defense: 2, speed: 1.2, exp: 22, coin: 25 },
    ],
  },

  dark_forest: {
    id: 'dark_forest',
    name: 'DARK FOREST',
    subtitle: 'Hutan Gelap Berkabut & Sarang Monster Buas',
    width: 2000,
    height: 1200,
    bgFill: '#1e1b4b', // Dark purple/indigo forest floor
    musicTrack: 'dark_forest',
    npcs: [],
    portals: [
      {
        id: 'portal_back_gf',
        x: 40,
        y: 480,
        width: 40,
        height: 60,
        targetArea: 'green_forest',
        targetX: 1840,
        targetY: 480,
        label: '◀ KEMBALI KE GREEN FOREST',
      },
      {
        id: 'portal_to_ruins',
        x: 1920,
        y: 480,
        width: 40,
        height: 60,
        targetArea: 'ruins',
        targetX: 80,
        targetY: 480,
        label: 'MENUJU ANCIENT RUINS ▶',
      },
    ],
    chests: [
      { id: 'chest_df1', x: 600, y: 200, opened: false, coin: 250, item: INITIAL_POTIONS[1] },
      { id: 'chest_df2', x: 1400, y: 850, opened: false, coin: 300 },
    ],
    monsterSpawns: [
      { type: 'dark_slime', name: 'Dark Slime', x: 280, y: 350, hp: 90, damage: 18, defense: 4, speed: 1.2, exp: 40, coin: 40 },
      { type: 'wolf', name: 'Dire Wolf', x: 450, y: 700, hp: 110, damage: 22, defense: 4, speed: 2.1, exp: 55, coin: 50 },
      { type: 'goblin_warrior', name: 'Goblin Warrior', x: 750, y: 380, hp: 130, damage: 25, defense: 7, speed: 1.4, exp: 65, coin: 60 },
      { type: 'skeleton', name: 'Skeleton Grunt', x: 950, y: 720, hp: 120, damage: 24, defense: 5, speed: 1.3, exp: 60, coin: 55 },
      { type: 'wolf', name: 'Dire Wolf', x: 1200, y: 320, hp: 110, damage: 22, defense: 4, speed: 2.1, exp: 55, coin: 50 },
      { type: 'dark_slime', name: 'Dark Slime', x: 1400, y: 750, hp: 90, damage: 18, defense: 4, speed: 1.2, exp: 40, coin: 40 },
      // Mini Boss: Forest Guardian
      {
        type: 'forest_guardian',
        name: 'Forest Guardian',
        x: 1650,
        y: 480,
        hp: 450,
        damage: 32,
        defense: 10,
        speed: 1.2,
        exp: 300,
        coin: 350,
        isBoss: true,
        bossTitle: 'PENJAGA HUTAN PURBA (MINI BOSS)',
      },
    ],
  },

  ruins: {
    id: 'ruins',
    name: 'ANCIENT RUINS',
    subtitle: 'Reruntuhan Kerajaan Kuno Penuh Prajurit Tengkorak',
    width: 2000,
    height: 1200,
    bgFill: '#334155', // Slate stones and broken marble
    musicTrack: 'ruins',
    npcs: [],
    portals: [
      {
        id: 'portal_back_df',
        x: 40,
        y: 480,
        width: 40,
        height: 60,
        targetArea: 'dark_forest',
        targetX: 1840,
        targetY: 480,
        label: '◀ KEMBALI KE DARK FOREST',
      },
      {
        id: 'portal_to_demon_territory',
        x: 1920,
        y: 480,
        width: 40,
        height: 60,
        targetArea: 'demon_territory',
        targetX: 80,
        targetY: 520,
        label: 'MENUJU DEMON TERRITORY ▶',
      },
    ],
    chests: [
      { id: 'chest_ruins1', x: 450, y: 200, opened: false, coin: 400, item: INITIAL_POTIONS[2] },
      { id: 'chest_ruins2', x: 1500, y: 850, opened: false, coin: 450 },
    ],
    monsterSpawns: [
      { type: 'skeleton_archer', name: 'Skeleton Archer', x: 320, y: 350, hp: 140, damage: 28, defense: 5, speed: 1.4, exp: 75, coin: 70 },
      { type: 'skeleton_knight', name: 'Skeleton Knight', x: 550, y: 650, hp: 200, damage: 32, defense: 12, speed: 1.3, exp: 95, coin: 85 },
      { type: 'dark_mage', name: 'Dark Cultist Mage', x: 800, y: 320, hp: 150, damage: 35, defense: 6, speed: 1.3, exp: 90, coin: 80 },
      { type: 'skeleton_knight', name: 'Skeleton Knight', x: 1050, y: 720, hp: 200, damage: 32, defense: 12, speed: 1.3, exp: 95, coin: 85 },
      { type: 'dark_mage', name: 'Dark Cultist Mage', x: 1300, y: 350, hp: 150, damage: 35, defense: 6, speed: 1.3, exp: 90, coin: 80 },
      // Boss: Skeleton King
      {
        type: 'skeleton_king',
        name: 'Skeleton King',
        x: 1650,
        y: 480,
        hp: 750,
        damage: 42,
        defense: 16,
        speed: 1.4,
        exp: 500,
        coin: 500,
        isBoss: true,
        bossTitle: 'RAJA TENGKORAK PURBA (BOSS)',
      },
    ],
  },

  demon_territory: {
    id: 'demon_territory',
    name: 'DEMON TERRITORY',
    subtitle: 'Wilayah Kegelapan Berlahar & Tanah Dikutuk Raja Iblis',
    width: 2200,
    height: 1300,
    bgFill: '#450a0a', // Scorched crimson earth
    musicTrack: 'demon_territory',
    npcs: [],
    portals: [
      {
        id: 'portal_back_ruins',
        x: 40,
        y: 520,
        width: 40,
        height: 60,
        targetArea: 'ruins',
        targetX: 1840,
        targetY: 480,
        label: '◀ KEMBALI KE RUINS',
      },
      {
        id: 'portal_to_demon_castle',
        x: 2120,
        y: 520,
        width: 40,
        height: 60,
        targetArea: 'demon_castle',
        targetX: 80,
        targetY: 520,
        label: 'GERBANG DEMON CASTLE ▶',
      },
    ],
    chests: [
      { id: 'chest_dt1', x: 500, y: 250, opened: false, coin: 550, item: INITIAL_POTIONS[2] },
      { id: 'chest_dt2', x: 1600, y: 950, opened: false, coin: 600 },
    ],
    monsterSpawns: [
      { type: 'demon', name: 'Lesser Demon', x: 350, y: 400, hp: 240, damage: 40, defense: 14, speed: 1.6, exp: 120, coin: 100 },
      { type: 'demon', name: 'Lesser Demon', x: 600, y: 750, hp: 240, damage: 40, defense: 14, speed: 1.6, exp: 120, coin: 100 },
      { type: 'dark_mage', name: 'Infernal Sorcerer', x: 900, y: 350, hp: 220, damage: 45, defense: 10, speed: 1.4, exp: 130, coin: 110 },
      { type: 'demon', name: 'Lesser Demon', x: 1200, y: 800, hp: 240, damage: 40, defense: 14, speed: 1.6, exp: 120, coin: 100 },
      { type: 'demon', name: 'Lesser Demon', x: 1450, y: 380, hp: 240, damage: 40, defense: 14, speed: 1.6, exp: 120, coin: 100 },
      // Boss: Demon General
      {
        type: 'demon_general',
        name: 'Demon General Malgor',
        x: 1850,
        y: 520,
        hp: 1100,
        damage: 55,
        defense: 22,
        speed: 1.5,
        exp: 700,
        coin: 750,
        isBoss: true,
        bossTitle: 'PANGLIMA RAJA IBLIS (BOSS)',
      },
    ],
  },

  demon_castle: {
    id: 'demon_castle',
    name: 'DEMON CASTLE (FINAL AREA)',
    subtitle: 'Kastil Megah Raja Iblis & Ruang Pertempuran Terakhir',
    width: 2200,
    height: 1300,
    bgFill: '#180202', // Obsidian dark throne room
    musicTrack: 'boss',
    npcs: [],
    portals: [
      {
        id: 'portal_back_dt',
        x: 40,
        y: 520,
        width: 40,
        height: 60,
        targetArea: 'demon_territory',
        targetX: 2040,
        targetY: 520,
        label: '◀ KEMBALI KE DEMON TERRITORY',
      },
    ],
    chests: [
      { id: 'chest_dc1', x: 450, y: 250, opened: false, coin: 800, item: INITIAL_POTIONS[2] },
      { id: 'chest_dc2', x: 450, y: 800, opened: false, coin: 800, item: INITIAL_POTIONS[2] },
    ],
    monsterSpawns: [
      { type: 'demon', name: 'Elite Demon Guard', x: 480, y: 400, hp: 300, damage: 48, defense: 18, speed: 1.7, exp: 150, coin: 130 },
      { type: 'demon', name: 'Elite Demon Guard', x: 480, y: 650, hp: 300, damage: 48, defense: 18, speed: 1.7, exp: 150, coin: 130 },
      { type: 'dark_mage', name: 'Demon High Priest', x: 800, y: 400, hp: 280, damage: 52, defense: 14, speed: 1.5, exp: 160, coin: 140 },
      { type: 'dark_mage', name: 'Demon High Priest', x: 800, y: 650, hp: 280, damage: 52, defense: 14, speed: 1.5, exp: 160, coin: 140 },
      // THE FINAL BOSS: DEMON KING!
      {
        type: 'demon_king',
        name: 'DEMON KING MORGATH',
        x: 1800,
        y: 520,
        hp: 2400,
        damage: 65,
        defense: 28,
        speed: 1.6,
        exp: 2500,
        coin: 2000,
        isBoss: true,
        bossTitle: 'PENGUASA KEGELAPAN (FINAL BOSS)',
      },
    ],
  },
};
